general {
  lock_cmd = ~/.config/hypr/scripts/hyprlock-current-wall.sh

  # suspend/resume hooks:
  before_sleep_cmd = ~/.config/hypr/scripts/hyprlock-current-wall.sh
  after_sleep_cmd  = ~/.config/hypr/scripts/hyprlock-current-wall.sh
}

# lock after 10 minutes idle
listener {
  timeout = 600
  on-timeout = ~/.config/hypr/scripts/hyprlock-current-wall.sh
}
